### ISSUE TITLE
I got the error like this "Video [7IG5kRFIMZw] is not available and cannot be processed. Code: 0. Reason: null." , what should i do - please help

### ISSUE THREAD

**Issue by Hendaru** [SoundByteOSS/youtube-extractor#11]
E/flutter (27412): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Video [7IG5kRFIMZw] is not available and cannot be processed. Code: 0. Reason: null.

**Comment by DominicMaas** [comment]
I've published a new version, let me know if it works.

**Comment by Hendaru** [comment]
> I've published a new version, let me know if it works.

thank you very much, it works :)
