### ISSUE TITLE
VideoUnavailableException (Video [U_MVuEJqpOA] is not available and cannot be processed. Code: 0. Reason: null.)

### ISSUE THREAD

**Issue by ferysyukur** [SoundByteOSS/youtube-extractor#13]
I got this issue: VideoUnavailableException (Video [U_MVuEJqpOA] is not available and cannot be processed. Code: 0. Reason: null.). What can i do for this issue ?

**Comment by DominicMaas** [comment]
I've published a new version, let me know if it works.

**Comment by ferysyukur** [comment]
Thank you, it's working now.
