### ISSUE TITLE
The method 'group' was called on null.

### ISSUE THREAD

**Issue by davidgalarza** [SoundByteOSS/youtube-extractor#2]
I'm getting this error again and It does not work anymore, I'm receiving the following error:

): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (23690): NoSuchMethodError: The method 'group' was called on null.
E/flutter (23690): Receiver: null
E/flutter (23690): Tried calling: group(1)
E/flutter (23690): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (23690): #1      PlayerSourceParser.parseCipherOperations (package:youtube_extractor/src/internal/parsers/player_source_parser.dart:22:10)
E/flutter (23690): #2      YouTubeExtractor._getVideoPlayerSourceAsync (package:youtube_extractor/youtube_extractor.dart:298:29)
E/flutter (23690): <asynchronous suspension>
E/flutter (23690): #3      YouTubeExtractor.getMediaStreamsAsync (package:youtube_extractor/youtube_extractor.dart:73:19)
E/flutter (23690): <asynchronous suspension>

The last time that I got this error have been a YouTube API change.

**Comment by DominicMaas** [comment]
Thanks for the pull request, I've published the updated package.
