### ISSUE TITLE
i got the error like this, what should i do

### ISSUE THREAD

**Issue by zaifullahbandung** [SoundByteOSS/youtube-extractor#8]
Unhandled Exception: Video [HZ7PAyCDwEg] is not available and cannot be processed. Code: 2. Reason: Invalid parameters..

**Comment by zaifullahbandung** [comment]
and this is the full error

E/flutter (18797): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Video [rnMhnbcU7vo] is not available and cannot be processed. Code: 2. Reason: Invalid parameters..
E/flutter (18797): #0      YouTubeExtractor._getVideoInfoParserAsync (package:youtube_extractor/youtube_extractor.dart:266:7)
E/flutter (18797): <asynchronous suspension>
E/flutter (18797): #1      YouTubeExtractor.getMediaStreamsAsync (package:youtube_extractor/youtube_extractor.dart:42:15)
E/flutter (18797): <asynchronous suspension>
E/flutter (18797): #2      _MyHomePageState.ambil (package:chewie_sample/main.dart:53:42)
E/flutter (18797): <asynchronous suspension>
E/flutter (18797): #3      _MyHomePageState.initState (package:chewie_sample/main.dart:47:5)
E/flutter (18797): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
E/flutter (18797): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (18797): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (18797): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (18797): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (18797): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (18797): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (18797): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (18797): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (18797): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (18797): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (18797): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (18797): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (18797): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (18797): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (18797): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (18797): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (18797): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (18797): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (18797): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (18797): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (18797): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (18797): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (18797): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (18797): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (18797): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (18797): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (18797): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (18797): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter (18797): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (18797): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (18797): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (18797): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (18797): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (18797): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (18797): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (18797): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (18797): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (18797): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (18797): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (18797): #44     ComponentElement._firstBuild (pa

**Comment by greentornado** [comment]
Error at this line: https://github.com/SoundByteOSS/youtube-extractor/blob/master/lib/youtube_extractor.dart#L262

The result return from youtube is `reason=Invalid+parameters.&status=fail&errorcode=2`

----
Should be changed to `https://www.youtube.com/get_video_info?video_id=$videoId`

**Comment by DominicMaas** [comment]
Published the fixed package
